name: Test Stream Extractor

on:
  workflow_dispatch:

jobs:
  run-extractor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install axios unpacker

      - name: Run Extractor Script
        run: node parser.js
